name: Caliptra Security
run-name: caliptra-ci[bot]
on:
  workflow_dispatch:
    inputs:
      client_payload:
        description: The Client payload
        required: true

permissions:
  contents: read
  security-events: write
  pull-requests: write
  packages: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: caliptrasecurity/caliptra-action-scanner@v1
        with:
          github_context: ${{ toJSON(github) }}
          inputs_context: ${{ toJSON(inputs) }}