name: Caliptra Security Check

on:
  push:
    branches: [main]  # For merges and direct commits to main
  pull_request:
    branches: [main]  # For pull requests
# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#     branches: [main]
  schedule:
    - cron: "0 0 * * *" # Optional: Runs the workflow daily as a scheduled task

env:
  REGISTRY: ghcr.io
  SCANNER_IMAGE: ghcr.io/caliptrasecurity/agent:main

jobs:
  caliptra-security:
    name: Caliptra Security
    runs-on: ubuntu-latest
    permissions:
      contents: read          # Required to read repository contents
      security-events: write  # Allows creating security events
      pull-requests: write    # Allows updating PR statuses
      packages: read          # Pull container images from GitHub Packages

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull scanner image
        run: docker pull ${{ env.SCANNER_IMAGE }}

      - name: Run Dependency Scanner
        id: scanner
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/code \
            -e SCAN_PATH=${{ github.workspace }} \
            -e INPUT_FAIL_ON_SEVERITY=true \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_REF_NAME=${{ github.ref_name }} \
            -e GITHUB_SHA=${{ github.sha }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_EVENT_NAME=${{ github.event_name }} \
            -e GITHUB_OUTPUT=$GITHUB_OUTPUT \
            ${{ env.SCANNER_IMAGE }}
