name: Caliptra Security Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *" # Daily scan

env:
  REGISTRY: ghcr.io
  SCANNER_IMAGE: ghcr.io/caliptrasecurity/agent:main

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull scanner image
        run: docker pull ghcr.io/caliptrasecurity/agent:main

      - name: Run Dependency Scanner
        id: scanner
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/code \
            -e SCAN_PATH=/code \
            -e INPUT_FAIL_ON_SEVERITY=true \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_REF_NAME=${{ github.ref_name }} \
            -e GITHUB_OUTPUT=$GITHUB_OUTPUT \
            ${{ env.SCANNER_IMAGE }}
